// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyqk7zwQa9SO1SdlKa0fn7AOndv224qw8',
    appId: '1:785806298572:web:8f760df85a1be7f0fe6169',
    messagingSenderId: '785806298572',
    projectId: 'famcare-14987',
    authDomain: 'famcare-14987.firebaseapp.com',
    storageBucket: 'famcare-14987.firebasestorage.app',
    measurementId: 'G-94JRKEHYSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hBEIXO0cGT8PJhEGUM-uIalRAidMUrQ',
    appId: '1:785806298572:android:c3f1176a3e07a124fe6169',
    messagingSenderId: '785806298572',
    projectId: 'famcare-14987',
    storageBucket: 'famcare-14987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEmvSt899kNc2X9U1P2r_V-DPdm0UGMsg',
    appId: '1:785806298572:ios:9220314756fe8c9efe6169',
    messagingSenderId: '785806298572',
    projectId: 'famcare-14987',
    storageBucket: 'famcare-14987.firebasestorage.app',
    iosBundleId: 'com.example.famCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEmvSt899kNc2X9U1P2r_V-DPdm0UGMsg',
    appId: '1:785806298572:ios:9220314756fe8c9efe6169',
    messagingSenderId: '785806298572',
    projectId: 'famcare-14987',
    storageBucket: 'famcare-14987.firebasestorage.app',
    iosBundleId: 'com.example.famCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyqk7zwQa9SO1SdlKa0fn7AOndv224qw8',
    appId: '1:785806298572:web:7eafe7596e0d8410fe6169',
    messagingSenderId: '785806298572',
    projectId: 'famcare-14987',
    authDomain: 'famcare-14987.firebaseapp.com',
    storageBucket: 'famcare-14987.firebasestorage.app',
    measurementId: 'G-5RF32QGYEC',
  );
}
